<?php
if (!defined('__DEFINES'))
{
	define('__DEFINES',1);
	
	// id_privilegio	
	define('PRIV_BACKOFFICE',					1);
	define('PRIV_UTENTI_VEDI',					101);
	define('PRIV_UTENTI_INSERIMENTO',			102);
	define('PRIV_UTENTI_MODIFICA',				103);
	define('PRIV_UTENTI_MODIFICA_PROPRI',		104);
	define('PRIV_UTENTI_ELIMINA',				105);
	define('PRIV_UTENTI_ELIMINA_PROPRI',		106);
	define('PRIV_ARTICOLI_VEDI',				201);
	define('PRIV_ARTICOLI_INSERIMENTO',			202);
	define('PRIV_ARTICOLI_INSERIMENTO_PROPRI',	203);
	define('PRIV_ARTICOLI_MODIFICA',			204);
	define('PRIV_ARTICOLI_MODIFICA_PROPRI',		205);
	define('PRIV_ARTICOLI_ELIMINA',				206);
	define('PRIV_ARTICOLI_ELIMINA_PROPRI',		207);
	define('PRIV_COMMENTI_VEDI',				301);
	define('PRIV_COMMENTI_INSERIMENTO',			302);
	define('PRIV_COMMENTI_INSERIMENTO_PROPRI',	303);
	define('PRIV_COMMENTI_MODIFICA',			304);
	define('PRIV_COMMENTI_MODIFICA_PROPRI',		305);
	define('PRIV_COMMENTI_ELIMINA',				306);
	define('PRIV_COMMENTI_ELIMINA_PROPRI',		307);
	define('PRIV_ARGOMENTI_VEDI',				401);
	define('PRIV_ARGOMENTI_INSERIMENTO',		402);
	define('PRIV_ARGOMENTI_INSERIMENTO_PROPRI',	403);
	define('PRIV_ARGOMENTI_MODIFICA',			404);
	define('PRIV_ARGOMENTI_MODIFICA_PROPRI',	405);
	define('PRIV_ARGOMENTI_ELIMINA',			406);
	define('PRIV_ARGOMENTI_ELIMINA_PROPRI',		407);
	define('PRIV_INTERVENTI_VEDI',				501);
	define('PRIV_INTERVENTI_INSERIMENTO',		502);
	define('PRIV_INTERVENTI_INSERIMENTO_PROPRI',503);
	define('PRIV_INTERVENTI_MODIFICA',			504);
	define('PRIV_INTERVENTI_MODIFICA_PROPRI',	505);
	define('PRIV_INTERVENTI_ELIMINA',			506);
	define('PRIV_INTERVENTI_ELIMINA_PROPRI',	507);
	define('PRIV_DOCUMENTI_VEDI',				601);
	define('PRIV_DOCUMENTI_INSERIMENTO',		602);
	define('PRIV_DOCUMENTI_INSERIMENTO_PROPRI',	603);
	define('PRIV_DOCUMENTI_MODIFICA',			604);
	define('PRIV_DOCUMENTI_MODIFICA_PROPRI',	605);
	define('PRIV_DOCUMENTI_ELIMINA',			606);
	define('PRIV_DOCUMENTI_ELIMINA_PROPRI',		607);
	define('PRIV_CATEGORIE_ARTICOLI_VEDI',		1001);
	define('PRIV_CATEGORIE_ARTICOLI_INSERIMENTO',1002);
	define('PRIV_CATEGORIE_ARTICOLI_MODIFICA',	1003);
	define('PRIV_CATEGORIE_ARTICOLI_ELIMINA',	1004);
	define('PRIV_CATEGORIE_ARGOMENTI_VEDI',		1101);
	define('PRIV_CATEGORIE_ARGOMENTI_INSERIMENTO',1102);
	define('PRIV_CATEGORIE_ARGOMENTI_MODIFICA',	1103);
	define('PRIV_CATEGORIE_ARGOMENTI_ELIMINA',	1104);
	define('PRIV_HTML_BASE',					10001);
	define('PRIV_HTML_ESTESO',					10002);
	
		
} //  if (!defined('__DEFINES'))

